[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet('report', 'apply', 'restore')]
    [string]$Action = 'report',

    [string]$SiderAddons = $(if ($env:PES_GAME_ROOT) { Join-Path $env:PES_GAME_ROOT 'SiderAddons' } else { Join-Path ${env:ProgramFiles(x86)} 'SP Football Life 2026\SiderAddons' }),

    [switch]$AllGlobals,

    [switch]$Force
)

$ErrorActionPreference = 'Stop'

$script:Sentinel = '-- sider-lua-localize: file-scope locals, regenerated by tools/sider-lua-localize.ps1'

$script:LuaKeywords = @(
    'and', 'break', 'do', 'else', 'elseif', 'end', 'false', 'for', 'function', 'goto',
    'if', 'in', 'local', 'nil', 'not', 'or', 'repeat', 'return', 'then', 'true',
    'until', 'while'
)

$script:LocalPatterns = @(
    '\blocal\s+(?:function\s+)?([A-Za-z_]\w*(?:\s*,\s*[A-Za-z_]\w*)*)',
    '\bfunction\b[^(]*\(([^)]*)\)',
    '\bfor\s+([A-Za-z_]\w*(?:\s*,\s*[A-Za-z_]\w*)*)\s*(?:=|\bin\b)'
)

function Assert-Path {
    param([string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Path not found: $Path"
    }
}

function Get-SiderIniPath {
    param([string]$Root)

    Join-Path $Root 'sider.ini'
}

function Get-LoadedModule {
    param([string]$IniPath)

    Get-Content -LiteralPath $IniPath | ForEach-Object {
        if ($_ -match '^\s*lua\.module\s*=\s*"([^"]+)"') { $Matches[1] }
    }
}

function Get-BackupPath {
    param([string]$Path)

    "$Path.pre-localize.bak"
}

function Get-SourceLine {
    param([string]$Path)

    $backup = Get-BackupPath $Path
    $source = if (Test-Path -LiteralPath $backup) { $backup } else { $Path }
    $lines = Get-Content -LiteralPath $source

    , [string[]]@($lines | Where-Object { $null -ne $_ })
}

function Test-CodeLine {
    param([string]$Line)

    if ([string]::IsNullOrEmpty($Line)) { return $false }

    $trimmed = $Line.TrimStart()
    $trimmed.Length -gt 0 -and -not $trimmed.StartsWith('--')
}

function Get-DeclaredLocal {
    param([string[]]$Lines)

    $names = [System.Collections.Generic.HashSet[string]]::new()

    foreach ($line in $Lines) {
        if (-not (Test-CodeLine $line)) { continue }

        foreach ($pattern in $script:LocalPatterns) {
            foreach ($match in [regex]::Matches($line, $pattern)) {
                foreach ($name in $match.Groups[1].Value -split ',') {
                    $candidate = $name.Trim()

                    if ($candidate.Length -eq 0) { continue }
                    if ($script:LuaKeywords -contains $candidate) { continue }
                    if ($candidate -notmatch '^[A-Za-z_]\w*$') { continue }

                    [void]$names.Add($candidate)
                }
            }
        }
    }

    , $names
}

function Get-GlobalWrite {
    param([string[]]$Lines, [System.Collections.Generic.HashSet[string]]$Declared)

    $names = [System.Collections.Generic.HashSet[string]]::new()
    $depth = 0

    foreach ($line in $Lines) {
        $bare = if (Test-CodeLine $line) { Get-BareCode $line } else { '' }
        $outsideTable = $depth -eq 0

        $depth += ([regex]::Matches($bare, '\{')).Count
        $depth -= ([regex]::Matches($bare, '\}')).Count
        if ($depth -lt 0) { $depth = 0 }

        if (-not $outsideTable) { continue }

        $match = [regex]::Match($bare, '^[ \t]*([A-Za-z_]\w*(?:[ \t]*,[ \t]*[A-Za-z_]\w*)*)[ \t]*=(?!=)')
        if (-not $match.Success) { continue }

        foreach ($name in $match.Groups[1].Value -split ',') {
            $candidate = $name.Trim()

            if ($script:LuaKeywords -contains $candidate) { continue }
            if ($Declared.Contains($candidate)) { continue }

            [void]$names.Add($candidate)
        }
    }

    , $names
}

function Get-BareCode {
    param([string]$Line)

    $stripped = [regex]::Replace($Line, '"[^"]*"', '""')
    $stripped = [regex]::Replace($stripped, "'[^']*'", "''")

    $comment = $stripped.IndexOf('--')
    if ($comment -ge 0) { $stripped = $stripped.Substring(0, $comment) }

    $stripped
}

function Test-NameMentioned {
    param([string[]]$Lines, [string]$Name)

    $pattern = "(?<![\w.:])$([regex]::Escape($Name))(?![\w])(?![ \t]*=(?!=))"

    foreach ($line in $Lines) {
        if (-not (Test-CodeLine $line)) { continue }
        if ((Get-BareCode $line) -match $pattern) { return $true }
    }

    $false
}

function Test-SourceModule {
    param([string]$Path)

    $head = Get-Content -LiteralPath $Path -AsByteStream -TotalCount 4096

    if ($head.Count -eq 0) { return $false }
    if ($head[0] -eq 0x1B) { return $false }

    -not ($head -contains 0)
}

function Get-ModuleFact {
    param([string]$Root, [string[]]$Modules)

    foreach ($module in $Modules) {
        $path = Join-Path $Root (Join-Path 'modules' $module)

        if (-not (Test-Path -LiteralPath $path)) {
            Write-Warning "Loaded module missing on disk: $module"
            continue
        }

        if (-not (Test-SourceModule $path)) {
            Write-Warning "Skipping compiled or binary module: $module"
            continue
        }

        $lines = Get-SourceLine $path
        $declared = Get-DeclaredLocal $lines
        $globals = Get-GlobalWrite -Lines $lines -Declared $declared

        [pscustomobject]@{
            Module   = $module
            Path     = $path
            Lines    = $lines
            Declared = $declared
            Globals  = $globals
        }
    }
}

function Get-CollidingName {
    param([object[]]$Facts)

    $counts = [System.Collections.Generic.Dictionary[string, int]]::new([System.StringComparer]::Ordinal)

    foreach ($fact in $Facts) {
        foreach ($name in $fact.Globals) {
            $seen = 0
            [void]$counts.TryGetValue($name, [ref]$seen)
            $counts[$name] = $seen + 1
        }
    }

    $counts.GetEnumerator() | Where-Object { $_.Value -gt 1 } | ForEach-Object { $_.Key }
}

function Get-ForeignReader {
    param([object[]]$Facts, [string]$Name, [string]$Owner)

    foreach ($fact in $Facts) {
        if ($fact.Module -eq $Owner) { continue }
        if ($fact.Globals.Contains($Name)) { continue }
        if ($fact.Declared.Contains($Name)) { continue }
        if (Test-NameMentioned -Lines $fact.Lines -Name $Name) { $fact.Module }
    }
}

function Get-Plan {
    param([object[]]$Facts, [bool]$EveryGlobal, [bool]$SkipReaderCheck)

    $colliding = @(Get-CollidingName -Facts $Facts)

    foreach ($fact in $Facts) {
        $targets = [System.Collections.Generic.List[string]]::new()
        $skipped = [System.Collections.Generic.List[string]]::new()

        foreach ($name in ($fact.Globals | Sort-Object)) {
            if (-not $EveryGlobal -and $colliding -notcontains $name) { continue }

            $readers = @(Get-ForeignReader -Facts $Facts -Name $name -Owner $fact.Module)

            if ($readers.Count -gt 0 -and -not $SkipReaderCheck) {
                $skipped.Add(('{0} (read by {1})' -f $name, ($readers -join ', ')))
                continue
            }

            $targets.Add($name)
        }

        [pscustomobject]@{
            Module  = $fact.Module
            Path    = $fact.Path
            Lines   = $fact.Lines
            Targets = $targets
            Skipped = $skipped
        }
    }
}

function Get-InsertIndex {
    param([string[]]$Lines)

    $index = 0

    while ($index -lt $Lines.Count) {
        $trimmed = $Lines[$index].TrimStart()
        if ($trimmed.Length -eq 0 -or $trimmed.StartsWith('--')) { $index++; continue }
        break
    }

    $index
}

function Add-LocalDeclaration {
    param([string]$Path, [string[]]$Lines, [string[]]$Names)

    $declaration = 'local {0}' -f (($Names | Sort-Object) -join ', ')
    $kept = [System.Collections.Generic.List[string]]::new()
    $index = 0

    while ($index -lt $Lines.Count) {
        if ($Lines[$index].Trim() -eq $script:Sentinel) {
            $index += 2
            continue
        }

        $kept.Add($Lines[$index])
        $index++
    }

    $at = Get-InsertIndex -Lines $kept
    $kept.Insert($at, $declaration)
    $kept.Insert($at, $script:Sentinel)

    $backup = Get-BackupPath $Path
    if (-not (Test-Path -LiteralPath $backup)) {
        Copy-Item -LiteralPath $Path -Destination $backup
    }

    Set-Content -LiteralPath $Path -Value $kept -Encoding utf8NoBOM
}

function Invoke-Report {
    param([object[]]$Plan)

    $rows = foreach ($item in $Plan) {
        if ($item.Targets.Count -eq 0 -and $item.Skipped.Count -eq 0) { continue }

        [pscustomobject]@{
            Module    = $item.Module
            Localize  = ($item.Targets -join ' ')
            Skipped   = ($item.Skipped -join '; ')
            Patched   = Test-Path -LiteralPath (Get-BackupPath $item.Path)
        }
    }

    if (-not $rows) {
        Write-Information 'No shared globals found in the loaded module set.' -InformationAction Continue
        return
    }

    $rows | Format-Table -AutoSize -Wrap
}

function Invoke-Apply {
    param([object[]]$Plan)

    $changed = 0

    foreach ($item in $Plan) {
        if ($item.Targets.Count -eq 0) { continue }

        Add-LocalDeclaration -Path $item.Path -Lines $item.Lines -Names $item.Targets
        $changed++

        Write-Information ('localized {0}: {1}' -f $item.Module, ($item.Targets -join ', ')) -InformationAction Continue
    }

    Write-Information ('modules patched: {0}' -f $changed) -InformationAction Continue
}

function Invoke-Restore {
    param([object[]]$Facts)

    $restored = 0

    foreach ($fact in $Facts) {
        $backup = Get-BackupPath $fact.Path
        if (-not (Test-Path -LiteralPath $backup)) { continue }

        Copy-Item -LiteralPath $backup -Destination $fact.Path -Force
        Remove-Item -LiteralPath $backup -Force
        $restored++

        Write-Information ('restored {0}' -f $fact.Module) -InformationAction Continue
    }

    Write-Information ('modules restored: {0}' -f $restored) -InformationAction Continue
}

Assert-Path $SiderAddons
$iniPath = Get-SiderIniPath $SiderAddons
Assert-Path $iniPath

$modules = @(Get-LoadedModule -IniPath $iniPath)
if ($modules.Count -eq 0) {
    throw "No lua.module entries in $iniPath"
}

$facts = @(Get-ModuleFact -Root $SiderAddons -Modules $modules)

$planArgs = @{
    Facts           = $facts
    EveryGlobal     = [bool]$AllGlobals
    SkipReaderCheck = [bool]$Force
}

switch ($Action) {
    'report' { Invoke-Report -Plan @(Get-Plan @planArgs) }
    'apply' { Invoke-Apply -Plan @(Get-Plan @planArgs) }
    'restore' { Invoke-Restore -Facts $facts }
}
